channels:
- conda-forge
dependencies:
- python=3.13.5
- pip<=25.1.1
- pip:
  - mlflow==3.6.0
  - cloudpickle==3.1.2
  - numpy==2.2.6
  - opencv-python-headless==4.12.0.88
  - pandas==2.3.3
  - pydot==4.0.1
  - pyreadline3==3.5.4
  - torch==2.9.1
  - tqdm==4.67.1
  - ultralytics==8.3.229
name: mlflow-env
